keywords = {
    "students": ["course", "courses", "lesson", "lessons", "subject", "subjects", "student", "students", "education",
        "class", "classes", "study", "studies", "enrollment", "attendee", "attendees", "academic", "attendance", ],
    "exams_regulations": ["regulation", "regulations", "exam regulation", "exam regulations", "test rule", "test rules",
        "exam policy", "exam policies", "testing procedure", "testing procedures", "assessment rule",
        "assessment rules", "evaluation guideline", "evaluation guidelines", "exam requirement", "exam requirements"],
    "interior_regulations": ["interior", "interior regulation", "interior regulations", "internal rule",
        "internal rules", "company policy", "company policies", "organizational rule", "organizational rules",
        "office guideline", "office guidelines", "code of conduct", "protocol", "protocols", "workplace regulation",
        "workplace regulations"],
    "fce_exam": ["fce", "fce exam", "fce examination", "cambridge english first", "cambridge fce", "fce test",
        "first certificate in english", "english proficiency test", "b2 exam", "fce preparation", "fce practice"],
    "delf_exam": ["delf", "delf exam", "delf examination", "diplôme d'études en langue française", "delf test",
        "french language exam", "french proficiency test", "delf preparation", "delf practice", "delf a1", "delf a2",
        "delf b1", "delf b2"], }
